services:
  postgres:
    image: postgres:14
    container_name: insightdeal-postgres
    restart: always
    environment:
      POSTGRES_USER: insightdeal
      POSTGRES_PASSWORD: password
      POSTGRES_DB: insightdeal
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - insightdeal-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U insightdeal"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: insightdeal-backend
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgresql://insightdeal:password@postgres:5432/insightdeal
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - FIREBASE_PROJECT_ID=${FIREBASE_PROJECT_ID}
      - FIREBASE_SERVICE_ACCOUNT_PATH=${FIREBASE_SERVICE_ACCOUNT_PATH}
      - FIREBASE_CREDENTIALS=${FIREBASE_CREDENTIALS}
      - FCM_SERVER_KEY=${FCM_SERVER_KEY}
      - PYTHONPATH=/app
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - ./backend/image_cache:/app/image_cache
    networks:
      - insightdeal-network
    restart: unless-stopped
    command: python -m uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  scheduler:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: insightdeal-scheduler
    depends_on:
      postgres:
        condition: service_healthy
      backend:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgresql://insightdeal:password@postgres:5432/insightdeal
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - FIREBASE_PROJECT_ID=${FIREBASE_PROJECT_ID}
      - FIREBASE_SERVICE_ACCOUNT_PATH=${FIREBASE_SERVICE_ACCOUNT_PATH}
      - FIREBASE_CREDENTIALS=${FIREBASE_CREDENTIALS}
      - PYTHONPATH=/app
    volumes:
      - ./backend:/app
    networks:
      - insightdeal-network
    restart: unless-stopped
    command: python -m scheduler.price_collector
    working_dir: /app

volumes:
  postgres_data:

networks:
  insightdeal-network:
    driver: bridge
