version: '3.8'
services:
  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: insightdeal
      POSTGRES_PASSWORD: password
      POSTGRES_DB: insightdeal
    ports:
      - "5432:5432"

  app:
    build: .
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://insightdeal:password@db:5432/insightdeal
    ports:
      - "8000:8000"
    volumes:
      - ./image_cache:/app/image_cache